// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTDsrBFxlPx7Iq6iBhRUb1xkrmL15LrS8',
    appId: '1:228862170675:web:d8a5410fa21e3deca77546',
    messagingSenderId: '228862170675',
    projectId: 'anime-app-28fe7',
    authDomain: 'anime-app-28fe7.firebaseapp.com',
    storageBucket: 'anime-app-28fe7.firebasestorage.app',
    measurementId: 'G-SKSQDXX76J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdi8yh5hvl_XalSK_ZvZcU0RH6AByrw04',
    appId: '1:228862170675:android:e334e47b03b3dbd0a77546',
    messagingSenderId: '228862170675',
    projectId: 'anime-app-28fe7',
    storageBucket: 'anime-app-28fe7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRda6efho_D0x8lQqwEecDYghTWZsYMgA',
    appId: '1:228862170675:ios:75285c78abb1459aa77546',
    messagingSenderId: '228862170675',
    projectId: 'anime-app-28fe7',
    storageBucket: 'anime-app-28fe7.firebasestorage.app',
    iosBundleId: 'com.example.animeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRda6efho_D0x8lQqwEecDYghTWZsYMgA',
    appId: '1:228862170675:ios:75285c78abb1459aa77546',
    messagingSenderId: '228862170675',
    projectId: 'anime-app-28fe7',
    storageBucket: 'anime-app-28fe7.firebasestorage.app',
    iosBundleId: 'com.example.animeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTDsrBFxlPx7Iq6iBhRUb1xkrmL15LrS8',
    appId: '1:228862170675:web:964da9c301d38e7ca77546',
    messagingSenderId: '228862170675',
    projectId: 'anime-app-28fe7',
    authDomain: 'anime-app-28fe7.firebaseapp.com',
    storageBucket: 'anime-app-28fe7.firebasestorage.app',
    measurementId: 'G-XJGCMWQ7VH',
  );
}
